import { useEffect, useId, useMemo, useRef, useState, type KeyboardEvent } from 'react'; import './Combobox.css';
export interface ComboboxOption { value:string; label:string; description?:string; disabled?:boolean; }
export interface ComboboxProps { options:ComboboxOption[]; value?:string; defaultValue?:string; onChange?:(value:string)=>void; label?:string; placeholder?:string; searchPlaceholder?:string; emptyText?:string; disabled?:boolean; clearable?:boolean; className?:string; }
export function Combobox({options,value:controlled,defaultValue='',onChange,label,placeholder='Select option',searchPlaceholder='Search...',emptyText='No options found',disabled=false,clearable=true,className=''}:ComboboxProps){
  const [internal,setInternal]=useState(defaultValue);const value=controlled??internal;const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const [active,setActive]=useState(0);const root=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLInputElement>(null);const id=useId();
  const filtered=useMemo(()=>options.filter(o=>`${o.label} ${o.description??''}`.toLowerCase().includes(query.toLowerCase())),[options,query]);const selected=options.find(o=>o.value===value);
  const commit=(next:string)=>{if(controlled===undefined)setInternal(next);onChange?.(next);setOpen(false);setQuery('')};
  useEffect(()=>{if(!open)return;setActive(0);queueMicrotask(()=>inputRef.current?.focus());const out=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',out);return()=>document.removeEventListener('pointerdown',out)},[open]);
  const onKey=(e:KeyboardEvent<HTMLInputElement>)=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(a=>Math.min(filtered.length-1,a+1))}else if(e.key==='ArrowUp'){e.preventDefault();setActive(a=>Math.max(0,a-1))}else if(e.key==='Enter'){e.preventDefault();const item=filtered[active];if(item&&!item.disabled)commit(item.value)}else if(e.key==='Escape'){setOpen(false)}};
  return <div className={`md-combobox ${className}`} ref={root}>{label&&<label className="md-combobox__label" htmlFor={`${id}-button`}>{label}</label>}<button id={`${id}-button`} type="button" className="md-combobox__trigger" onClick={()=>setOpen(v=>!v)} disabled={disabled} aria-expanded={open} aria-haspopup="listbox"><span className={selected?'':'is-placeholder'}>{selected?.label??placeholder}</span><span aria-hidden>⌄</span></button>{open&&<div className="md-combobox__menu"><div className="md-combobox__search"><span>⌕</span><input ref={inputRef} value={query} onChange={e=>{setQuery(e.target.value);setActive(0)}} onKeyDown={onKey} placeholder={searchPlaceholder} aria-label={searchPlaceholder}/></div><div className="md-combobox__list" role="listbox">{clearable&&value&&<button type="button" className="md-combobox__clear" onClick={()=>commit('')}>Clear selection</button>}{filtered.length?filtered.map((o,i)=><button type="button" role="option" aria-selected={o.value===value} className={`${i===active?'is-active':''} ${o.value===value?'is-selected':''}`} disabled={o.disabled} key={o.value} onMouseEnter={()=>setActive(i)} onClick={()=>commit(o.value)}><span><b>{o.label}</b>{o.description&&<small>{o.description}</small>}</span>{o.value===value&&<em>✓</em>}</button>):<div className="md-combobox__empty">{emptyText}</div>}</div></div>}</div>
}
