import { useMemo, useState, type ReactNode } from 'react'; import './DataTable.css';
export type DataTableKey = string | number;
export type DataTableSortDirection = 'asc' | 'desc';
export interface DataTableSort { key:string; direction:DataTableSortDirection; }
export interface DataTableColumn<T>{key:string;header:ReactNode;render:(row:T)=>ReactNode;align?:'left'|'center'|'right';width?:string;sortable?:boolean;sortValue?:(row:T)=>string|number|null|undefined}
export interface DataTableProps<T>{columns:DataTableColumn<T>[];rows:T[];getRowKey:(row:T)=>DataTableKey;empty?:ReactNode;onRowClick?:(row:T)=>void;compact?:boolean;striped?:boolean;stickyHeader?:boolean;sort?:DataTableSort|null;defaultSort?:DataTableSort|null;onSortChange?:(sort:DataTableSort|null)=>void;selectable?:boolean;selectedKeys?:DataTableKey[];defaultSelectedKeys?:DataTableKey[];onSelectedKeysChange?:(keys:DataTableKey[])=>void;caption?:string}
export function DataTable<T>({columns,rows,getRowKey,empty='No data available',onRowClick,compact=false,striped=false,stickyHeader=false,sort:controlledSort,defaultSort=null,onSortChange,selectable=false,selectedKeys:controlledSelected,defaultSelectedKeys=[],onSelectedKeysChange,caption}:DataTableProps<T>){
  const [internalSort,setInternalSort]=useState<DataTableSort|null>(defaultSort);const [internalSelected,setInternalSelected]=useState<DataTableKey[]>(defaultSelectedKeys);const sort=controlledSort===undefined?internalSort:controlledSort;const selected=controlledSelected??internalSelected;
  const sorted=useMemo(()=>{if(!sort)return rows;const col=columns.find(c=>c.key===sort.key);if(!col?.sortable)return rows;const accessor=col.sortValue??((row:T)=>(row as unknown as Record<string,unknown>)[col.key] as string|number|null|undefined);return [...rows].sort((a,b)=>{const av=accessor(a),bv=accessor(b);if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return-1;const cmp=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),undefined,{numeric:true,sensitivity:'base'});return sort.direction==='asc'?cmp:-cmp})},[rows,columns,sort]);
  const setSort=(key:string)=>{const next:DataTableSort=sort?.key===key?{key,direction:sort.direction==='asc'?'desc':'asc'}:{key,direction:'asc'};if(controlledSort===undefined)setInternalSort(next);onSortChange?.(next)};
  const setSelected=(keys:DataTableKey[])=>{if(controlledSelected===undefined)setInternalSelected(keys);onSelectedKeysChange?.(keys)};const allKeys=sorted.map(getRowKey);const allSelected=allKeys.length>0&&allKeys.every(k=>selected.includes(k));const someSelected=!allSelected&&allKeys.some(k=>selected.includes(k));const toggleAll=()=>setSelected(allSelected?selected.filter(k=>!allKeys.includes(k)):Array.from(new Set([...selected,...allKeys])));const toggle=(key:DataTableKey)=>setSelected(selected.includes(key)?selected.filter(k=>k!==key):[...selected,key]);
  return <div className={`md-table-wrap ${compact?'is-compact':''} ${striped?'is-striped':''} ${stickyHeader?'has-sticky-header':''}`}><table className="md-table">{caption&&<caption className="md-sr-only">{caption}</caption>}<thead><tr>{selectable&&<th className="md-table__select"><input type="checkbox" aria-label="Select all rows" checked={allSelected} ref={el=>{if(el)el.indeterminate=someSelected}} onChange={toggleAll}/></th>}{columns.map(c=><th key={c.key} style={{width:c.width,textAlign:c.align??'left'}}>{c.sortable?<button type="button" className="md-table__sort" onClick={()=>setSort(c.key)}><span>{c.header}</span><span aria-hidden>{sort?.key===c.key?(sort.direction==='asc'?'↑':'↓'):'↕'}</span></button>:c.header}</th>)}</tr></thead><tbody>{sorted.length?sorted.map(row=>{const key=getRowKey(row);return <tr key={key} onClick={()=>onRowClick?.(row)} className={`${onRowClick?'is-clickable':''} ${selected.includes(key)?'is-selected':''}`}>{selectable&&<td className="md-table__select" onClick={e=>e.stopPropagation()}><input type="checkbox" aria-label={`Select row ${key}`} checked={selected.includes(key)} onChange={()=>toggle(key)}/></td>}{columns.map(c=><td key={c.key} style={{textAlign:c.align??'left'}}>{c.render(row)}</td>)}</tr>}):<tr><td className="md-table__empty" colSpan={columns.length+(selectable?1:0)}>{empty}</td></tr>}</tbody></table></div>}
